### ISSUE TITLE
Your database design is vulnerable !

### ISSUE THREAD

**Issue by heyadityak** [rvsingh31/ExpenTrack#2]
I used a testing tool (ZAP) for testing your app. When the tool was running, i simply checked the database. Suddenly, all the passwords were 'ZAP%' (due to some attack). Since, you did not encrypted your passwords, the passwords were changed.

Here's the screenshot of the same : 
![capture](https://cloud.githubusercontent.com/assets/15857647/17828644/84dd482e-66b5-11e6-9bfb-2d7f065e9886.PNG)

**Comment by rvsingh31** [comment]
what if i use a password_hash?? will it do the same harm??

**Comment by rvsingh31** [comment]
I updated 2 files namely: logincheck.php and registeruser.php
I included an encryption class from the internet and included encryption decryption mechanism.
So, every new account will have their passwords encrypted from now on.
If u want , you can check it for the attacks and let me know if the attacks still takes place.
But yes, delete the old accounts and make new accounts again, and do update those 2 files and then again , perform the task. I hope it should work fine.
