### ISSUE TITLE
It's vulnerable to XSS & OS Command Injection

### ISSUE THREAD

**Issue by heyadityak** [rvsingh31/ExpenTrack#3]
Your app is also **_vulnerable to attacks like XSS (cross-site scripting) and Remote OS Command Injection attacks_** (As reported by tool - **ZAP**). The problems are only in the surface part of the website (without logging in to the actual app)

Here's the screenshot : 

![capture](https://cloud.githubusercontent.com/assets/15857647/17828681/4433b1f8-66b7-11e6-8abb-bd7a2b956a82.PNG)

**Comment by rvsingh31** [comment]
If its only on the surface part , then i guess its of no threat , because it didn't even entered the site ,ever feature was kind of protected.
Except the mail.php , which experienced Remote OS Command Injection.
Any ideas to secure that file ?

**Comment by rvsingh31** [comment]
index.php is just an introduction page with no mere responsibility except telling the users about the web-app and reporting a login or register error!
So , that file would be no problem ( according to me) ,then too, let me know some alternatives!

**Comment by rvsingh31** [comment]
I resolved that issue for XSS attacks. Its done ! Thanks.
